version: "3"
services:
  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: express-template
    ports:
      - "33306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: express
# docker-compose up
# docker-compose up --build
